# Wind Statistics

### Step 1. Import the necessary libraries

In [39]:
import pandas as pd 
import numpy as np
import datetime

### Step 2. Import the dataset from this address
### Step 3. Assign it to a variable called data and replace the first 3 columns by a proper datetime index.

In [28]:
data = pd.read_csv("https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/Wind_Stats/wind.data", 
                   sep = "\s+", parse_dates = [[0,1,2]])
# data = pd.read_csv("https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/Wind_Stats/wind.data", 
#                     sep = "\s+") 
data.Yr_Mo_Dy

0      2061-01-01
1      2061-01-02
2      2061-01-03
3      2061-01-04
4      2061-01-05
          ...
6569   1978-12-27
6570   1978-12-28
6571   1978-12-29
6572   1978-12-30
6573   1978-12-31
Name: Yr_Mo_Dy, Length: 6574, dtype: datetime64[ns]

### Step 4. Year 2061? Do we really have data from this year? Create a function to fix it and apply it.

In [53]:
data = pd.read_csv("https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/Wind_Stats/wind.data", 
                    sep = "\s+") 
data.Yr = data.Yr + 1900

df2 = data[['Yr','Mo','Dy']].copy()
df2.columns = ["year", "month", "day"]
data['Date'] = pd.to_datetime(df2)

data = data.iloc[:, 3:]
data
# data['Date'] = pd.to_datetime(data[['Yr','Mo','Dy']], format='%Y-%m-%d')


#Another answer 
# def fix_century(x):
#   year = x.year - 100 if x.year > 1989 else x.year
#   return datetime.date(year, x.month, x.day)

# # apply the function fix_century on the column and replace the values to the right ones
# data['Yr_Mo_Dy'] = data['Yr_Mo_Dy'].apply(fix_century)

# # data.info()
# data.head()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL,Date
0,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04,1961-01-01
1,14.71,NaN,10.83,6.50,12.62,7.67,11.50,10.04,9.79,9.67,17.54,13.83,1961-01-02
2,18.50,16.88,12.33,10.13,11.17,6.17,11.25,NaN,8.50,7.67,12.75,12.71,1961-01-03
3,10.58,6.63,11.75,4.58,4.54,2.88,8.63,1.79,5.83,5.88,5.46,10.88,1961-01-04
4,13.33,13.25,11.42,6.17,10.71,8.21,11.92,6.54,10.92,10.34,12.92,11.83,1961-01-05
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6569,17.58,16.96,17.62,8.08,13.21,11.67,14.46,15.59,14.04,14.00,17.21,40.08,1978-12-27
6570,13.21,5.46,13.46,5.00,8.12,9.42,14.33,16.25,15.25,18.05,21.79,41.46,1978-12-28
6571,14.00,10.29,14.42,8.71,9.71,10.54,19.17,12.46,14.50,16.42,18.88,29.58,1978-12-29
6572,18.50,14.04,21.29,9.13,12.75,9.71,18.08,12.87,12.46,12.12,14.67,28.79,1978-12-30
6573,20.33,17.41,27.29,9.59,12.08,10.13,19.25,11.63,11.58,11.38,12.08,22.08,1978-12-31

### Step 5. Set the right dates as the index. Pay attention at the data type, it should be datetime64[ns].

In [54]:
data.set_index("Date", inplace = True)

### Step 6. Compute how many values are missing for each location over the entire record.

In [55]:
data.isnull().sum()

RPT    6
VAL    3
ROS    2
KIL    5
SHA    2
BIR    0
DUB    3
CLA    2
MUL    3
CLO    1
BEL    0
MAL    4
dtype: int64

### Step 7. Compute how many non-missing values there are in total.

In [56]:
data.notnull().sum()

RPT    6568
VAL    6571
ROS    6572
KIL    6569
SHA    6572
BIR    6574
DUB    6571
CLA    6572
MUL    6571
CLO    6573
BEL    6574
MAL    6570
dtype: int64

### Step 8. Calculate the mean windspeeds of the windspeeds over all the locations and all the times.

In [61]:
data.sum().sum()/data.count().sum()

# Or data.sum().sum() / data.notna().sum().sum()

10.227883764282167

### Step 9. Create a DataFrame called loc_stats and calculate the min, max and mean windspeeds and standard deviations of the windspeeds at each location over all the days

In [72]:
loc_stats = data.describe().iloc[[3,7, 1, 2],:]

### Step 10. Create a DataFrame called day_stats and calculate the min, max and mean windspeed and standard deviations of the windspeeds across all the locations at each day.

In [101]:
min = data.min(axis=1)
max = data.max(axis=1)
mean = data.mean(axis=1)
std = data.std(axis=1)

data_stats = pd.concat([min, max, mean, std], axis = 1)
data_stats.columns = ['min', 'max', 'mean', 'std']
data_stats

             min    max       mean       std
Date
1961-01-01  9.29  18.50  13.018182  2.808875
1961-01-02  6.50  17.54  11.336364  3.188994
1961-01-03  6.17  18.50  11.641818  3.681912
1961-01-04  1.79  11.75   6.619167  3.198126
1961-01-05  6.17  13.33  10.630000  2.445356
...          ...    ...        ...       ...
1978-12-27  8.08  40.08  16.708333  7.868076
1978-12-28  5.00  41.46  15.150000  9.687857
1978-12-29  8.71  29.58  14.890000  5.756836
1978-12-30  9.13  28.79  15.367500  5.540437
1978-12-31  9.59  27.29  15.402500  5.702483

[6574 rows x 4 columns]

### Step 11. Find the average windspeed in January for each location.

In [108]:
data[data.index.month == 1].mean()

RPT    14.847325
VAL    12.914560
ROS    13.299624
KIL     7.199498
SHA    11.667734
BIR     8.054839
DUB    11.819355
CLA     9.512047
MUL     9.543208
CLO    10.053566
BEL    14.550520
MAL    18.028763
dtype: float64

### Step 12. Downsample the record to a yearly frequency for each location.

In [114]:
#https://kanoki.org/2020/05/26/dataframe-groupby-date-and-time/ 
# datetime handling 
data.groupby(pd.Grouper(freq="A")).mean()

#Or
#data.groupby(data.index.to_period('A')).mean()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
Date,,,,,,,,,,,,
1961-12-31,12.299583,10.351796,11.362369,6.958227,10.881763,7.729726,9.733923,8.858788,8.647652,9.835577,13.502795,13.680773
1962-12-31,12.246923,10.110438,11.732712,6.960440,10.657918,7.393068,11.020712,8.793753,8.316822,9.676247,12.930685,14.323956
1963-12-31,12.813452,10.836986,12.541151,7.330055,11.724110,8.434712,11.075699,10.336548,8.903589,10.224438,13.638877,14.999014
1964-12-31,12.363661,10.920164,12.104372,6.787787,11.454481,7.570874,10.259153,9.467350,7.789016,10.207951,13.740546,14.910301
1965-12-31,12.451370,11.075534,11.848767,6.858466,11.024795,7.478110,10.618712,8.879918,7.907425,9.918082,12.964247,15.591644
1966-12-31,13.461973,11.557205,12.020630,7.345726,11.805041,7.793671,10.579808,8.835096,8.514438,9.768959,14.265836,16.307260
1967-12-31,12.737151,10.990986,11.739397,7.143425,11.630740,7.368164,10.652027,9.325616,8.645014,9.547425,14.774548,17.135945
1968-12-31,11.835628,10.468197,11.409754,6.477678,10.760765,6.067322,8.859180,8.255519,7.224945,7.832978,12.808634,15.017486
1969-12-31,11.166356,9.723699,10.902000,5.767973,9.873918,6.189973,8.564493,7.711397,7.924521,7.754384,12.621233,15.762904
1970-12-31,12.600329,10.726932,11.730247,6.217178,10.567370,7.609452,9.609890,8.334630,9.297616,8.289808,13.183644,16.456027
1971-12-31,11.273123,9.095178,11.088329,5.241507,9.440329,6.097151,8.385890,6.757315,7.915370,7.229753,12.208932,15.025233
1972-12-31,12.463962,10.561311,12.058333,5.929699,9.430410,6.358825,9.704508,7.680792,8.357295,7.515273,12.727377,15.028716
1973-12-31,11.828466,10.680493,10.680493,5.547863,9.640877,6.548740,8.482110,7.614274,8.245534,7.812411,12.169699,15.441096
1974-12-31,13.643096,11.811781,12.336356,6.427041,11.110986,6.809781,10.084603,9.896986,9.331753,8.736356,13.252959,16.947671
1975-12-31,12.008575,10.293836,11.564712,5.269096,9.190082,5.668521,8.562603,7.843836,8.797945,7.382822,12.631671,15.307863
1976-12-31,11.737842,10.203115,10.761230,5.109426,8.846339,6.311038,9.149126,7.146202,8.883716,7.883087,12.332377,15.471448
1977-12-31,13.099616,11.144493,12.627836,6.073945,10.003836,8.586438,11.523205,8.378384,9.098192,8.821616,13.459068,16.590849
1978-12-31,12.504356,11.044274,11.380000,6.082356,10.167233,7.650658,9.489342,8.800466,9.089753,8.301699,12.967397,16.771370

### Step 13. Downsample the record to a monthly frequency for each location.

In [117]:
data.groupby(pd.Grouper(freq="M")).mean()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
Date,,,,,,,,,,,,
1961-01-31,14.841333,11.988333,13.431613,7.736774,11.072759,8.588065,11.184839,9.245333,9.085806,10.107419,13.880968,14.703226
1961-02-28,16.269286,14.975357,14.441481,9.230741,13.852143,10.937500,11.890714,11.846071,11.821429,12.714286,18.583214,15.411786
1961-03-31,10.890000,11.296452,10.752903,7.284000,10.509355,8.866774,9.644194,9.829677,10.294138,11.251935,16.410968,15.720000
1961-04-30,10.722667,9.427667,9.998000,5.830667,8.435000,6.495000,6.925333,7.094667,7.342333,7.237000,11.147333,10.278333
1961-05-31,9.860968,8.850000,10.818065,5.905333,9.490323,6.574839,7.604000,8.177097,8.039355,8.499355,11.900323,12.011613
...,...,...,...,...,...,...,...,...,...,...,...,...
1978-08-31,9.645161,8.259355,9.032258,4.502903,7.368065,5.935161,5.650323,5.417742,7.241290,5.536774,10.466774,12.054194
1978-09-30,10.913667,10.895000,10.635000,5.725000,10.372000,9.278333,10.790333,9.583000,10.069333,8.939000,15.680333,19.391333
1978-10-31,9.897742,8.670968,9.295806,4.721290,8.525161,6.774194,8.115484,7.337742,8.297742,8.243871,13.776774,17.150000
1978-11-30,16.151667,14.802667,13.508000,7.317333,11.475000,8.743000,11.492333,9.657333,10.701333,10.676000,17.404667,20.723000
1978-12-31,16.175484,13.748065,15.635161,7.094839,11.398710,9.241613,12.077419,10.194839,10.616774,11.028710,13.859677,21.371613

### Step 14. Downsample the record to a weekly frequency for each location.

In [121]:
data.groupby(pd.Grouper(freq="7D")).mean()

#data.groupby(data.index.to_period('W')).mean()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
Date,,,,,,,,,,,,
1961-01-01,14.124286,12.355000,11.280000,6.900000,9.450000,6.804286,10.972857,7.055000,8.660000,8.800000,12.750000,13.035714
1961-01-08,12.314286,8.978571,11.368571,5.135714,7.671429,5.667143,9.220000,6.932857,6.355714,8.261429,12.422857,12.411429
1961-01-15,13.554286,10.404286,13.244286,6.357143,9.051667,7.078571,8.274286,7.845714,6.918571,7.857143,9.344286,10.981429
1961-01-22,18.410000,13.565714,16.458571,10.524286,14.974286,12.800000,13.725714,13.272857,12.320000,13.861429,18.525714,20.607143
1961-01-29,15.965000,16.482857,12.988571,9.091429,14.765714,10.201429,13.352857,9.221429,10.977143,10.434286,15.210000,13.180000
...,...,...,...,...,...,...,...,...,...,...,...,...
1978-12-03,20.210000,19.018571,17.207143,9.342857,15.452857,12.982857,15.044286,12.655714,13.810000,14.272857,17.851429,23.608571
1978-12-10,18.908571,17.454286,16.201429,8.690000,13.190000,9.052857,11.744286,9.775714,11.300000,10.494286,14.114286,17.397143
1978-12-17,11.327143,7.662857,12.590000,3.635714,7.532857,5.522857,6.400000,7.554286,5.788571,6.781429,10.857143,15.744286
1978-12-24,13.285714,10.118571,13.868571,5.821429,8.661429,8.017143,12.708571,10.137143,10.761429,11.518571,12.924286,28.220000
1978-12-31,20.330000,17.410000,27.290000,9.590000,12.080000,10.130000,19.250000,11.630000,11.580000,11.380000,12.080000,22.080000

### Step 15. Calculate the min, max and mean windspeeds and standard deviations of the windspeeds across all locations for each week (assume that the first week starts on January 2 1961) for the first 52 weeks.

In [135]:
data.resample('W').agg(['min', 'max', 'mean', 'std'])  #resample & agg ì‚¬ìš©í•˜ëŠ”ê²Œ í•µì‹¬!!!**** 
data.iloc[1:53:]

#ì°¸ì¡°: https://rfriend.tistory.com/494

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
Date,,,,,,,,,,,,
1961-01-02,14.71,NaN,10.83,6.50,12.62,7.67,11.50,10.04,9.79,9.67,17.54,13.83
1961-01-03,18.50,16.88,12.33,10.13,11.17,6.17,11.25,NaN,8.50,7.67,12.75,12.71
1961-01-04,10.58,6.63,11.75,4.58,4.54,2.88,8.63,1.79,5.83,5.88,5.46,10.88
1961-01-05,13.33,13.25,11.42,6.17,10.71,8.21,11.92,6.54,10.92,10.34,12.92,11.83
1961-01-06,13.21,8.12,9.96,6.67,5.37,4.50,10.67,4.42,7.17,7.50,8.12,13.17
1961-01-07,13.50,14.29,9.50,4.96,12.29,8.33,9.17,9.29,7.58,7.96,13.96,13.79
1961-01-08,10.96,9.75,7.62,5.91,9.62,7.29,14.29,7.62,9.25,10.46,16.62,16.46
1961-01-09,12.58,10.83,10.00,4.75,10.37,6.79,8.04,10.13,7.79,9.08,13.04,15.37
1961-01-10,13.37,11.12,19.50,8.33,9.71,6.54,11.42,7.79,8.54,9.00,8.58,11.83
1961-01-11,10.58,9.87,8.42,2.79,8.71,7.25,7.54,8.33,5.71,8.67,20.71,16.92
1961-01-12,19.75,12.08,18.50,10.54,10.29,9.46,15.54,11.50,10.37,14.58,15.59,14.09
1961-01-13,9.92,3.54,8.46,2.96,2.29,0.96,4.63,0.58,2.33,3.37,5.25,7.04
1961-01-14,9.04,5.66,7.08,0.67,2.71,1.38,3.08,2.58,0.50,2.67,7.17,5.17
1961-01-15,12.04,9.67,11.75,2.37,7.38,3.13,2.50,6.83,4.75,5.63,7.54,6.75
1961-01-16,16.42,11.25,15.67,4.71,11.34,6.92,9.25,8.79,8.21,7.33,13.04,9.04
1961-01-17,17.75,14.37,17.33,10.13,13.96,13.37,13.42,11.04,8.71,11.38,15.92,16.08
1961-01-18,19.83,12.04,20.79,18.54,NaN,10.29,17.83,11.38,14.67,16.71,8.79,17.96
1961-01-19,4.92,3.42,7.29,1.04,3.67,3.17,3.71,2.79,1.92,2.71,6.87,7.83
1961-01-20,9.59,11.83,7.96,1.58,7.92,5.00,3.17,4.92,3.13,3.37,6.50,6.79
1961-01-21,14.33,10.25,11.92,6.13,10.04,7.67,8.04,9.17,7.04,7.87,6.75,12.42
1961-01-22,9.59,5.88,9.92,2.17,6.87,5.50,9.38,7.04,6.34,7.50,10.88,9.92
1961-01-23,16.54,9.96,18.54,10.46,13.50,12.67,13.70,13.75,10.75,13.17,14.79,20.58
1961-01-24,25.04,14.83,25.84,15.67,21.46,18.58,20.38,19.38,15.37,15.12,23.09,25.25
1961-01-25,13.62,11.17,12.67,6.04,10.00,9.42,9.25,8.71,7.12,12.04,14.04,17.50
1961-01-26,24.37,18.79,17.50,14.25,18.91,15.67,14.33,15.16,16.08,19.08,20.50,25.25
1961-01-27,22.04,20.79,17.41,16.21,19.04,16.13,16.79,18.29,18.66,19.08,26.08,27.63
1961-01-28,17.67,13.54,13.33,8.87,15.04,11.63,12.25,10.58,11.92,11.04,20.30,18.12
1961-01-29,NaN,23.91,22.29,17.54,24.08,19.70,22.00,20.25,21.46,19.95,27.71,23.38
1961-01-30,12.21,11.42,10.92,7.92,13.08,9.62,14.50,10.21,9.92,11.96,18.88,19.25
1961-01-31,24.21,19.55,16.71,11.96,14.42,10.46,14.88,8.21,10.50,9.96,12.42,13.92
1961-02-01,14.25,15.12,9.04,5.88,12.08,7.17,10.17,3.63,6.50,5.50,9.17,8.00
1961-02-02,20.17,24.21,10.00,6.54,17.37,7.17,10.88,6.08,9.08,7.12,12.08,7.17
1961-02-03,14.37,11.71,11.04,5.09,9.87,5.83,8.50,5.13,6.34,7.38,9.71,8.83
1961-02-04,10.58,9.46,10.92,8.71,12.46,11.46,12.54,11.04,13.04,11.17,16.50,11.71
1961-02-05,22.00,16.75,19.70,11.63,14.25,12.04,13.96,15.54,13.37,13.13,19.33,14.67
1961-02-06,24.50,20.75,20.62,15.37,25.33,17.62,19.17,18.79,18.96,14.46,26.38,21.84
1961-02-07,18.05,14.37,14.88,9.75,10.96,11.17,14.21,9.71,13.04,12.25,15.21,17.58
1961-02-08,24.54,21.42,21.34,11.63,17.04,14.21,16.50,17.33,14.67,17.79,23.79,19.58
1961-02-09,17.41,15.92,13.67,10.71,14.00,12.92,14.37,15.71,14.46,14.67,23.04,19.21
1961-02-10,20.50,11.54,19.67,10.04,8.12,8.08,11.08,12.54,11.12,12.96,17.83,17.75
1961-02-11,16.79,14.00,13.70,9.54,15.83,13.29,17.50,15.50,15.83,14.33,21.17,21.09
1961-02-12,16.00,16.92,17.25,8.38,11.75,10.37,11.71,14.37,10.37,14.62,25.41,17.04
1961-02-13,22.50,19.70,19.41,15.34,16.13,14.62,16.08,14.12,13.96,16.58,28.62,19.67
1961-02-14,17.08,11.63,17.25,12.12,13.75,13.46,15.46,12.29,14.88,15.67,14.09,11.42
1961-02-15,6.04,12.08,6.13,4.21,9.87,6.92,5.17,7.41,8.17,9.21,17.12,10.96
1961-02-16,16.79,20.17,12.67,13.25,15.29,15.12,3.42,14.29,14.79,13.79,21.92,22.58
1961-02-17,15.25,14.09,14.75,9.54,14.62,12.92,6.17,12.58,13.25,14.54,18.21,17.67
1961-02-18,12.08,12.38,12.67,6.04,10.71,9.08,10.88,12.38,10.00,11.34,18.58,13.25
1961-02-19,16.17,15.59,13.70,NaN,13.50,10.96,9.62,11.83,11.58,13.67,29.63,20.54
1961-02-20,11.04,11.08,10.63,8.33,10.92,8.29,7.25,7.75,8.83,11.08,15.09,12.17
1961-02-21,7.79,8.63,6.08,2.21,7.41,4.33,3.75,7.04,4.50,7.41,12.12,6.67
1961-02-22,12.29,13.21,13.54,6.46,11.58,9.21,8.25,10.29,9.21,13.08,15.25,13.21